<?php
$status = session_status();
if ($status === PHP_SESSION_NONE) {
    session_start();
}
$supported = ['en', 'fr', 'de', 'it'];
$lang = $_GET['lang'] ?? ($_SESSION['lang'] ?? 'en');
if (!in_array($lang, $supported)) {
    $lang = 'en';
}
$_SESSION['lang'] = $lang;
$translations = [
    'en' => [
        'login_title' => 'CVLG Login',
        'email' => 'Email',
        'password' => 'Password',
        'login' => 'Login',
        'welcome' => 'Welcome',
        'logged_in' => 'You are logged in.',
        'logout' => 'Logout',
        'member_management' => 'Member Management',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'member_type' => 'Member Type',
        'address' => 'Address',
        'street' => 'Street',
        'street_number' => 'Street Number',
        'postal_code' => 'Postal Code',
        'city' => 'City',
        'country' => 'Country',
        'add_member' => 'Add Member',
        'vehicle_management' => 'Vehicle Management',
        'add_vehicle' => 'Add Vehicle',
        'name' => 'Name',
        'registration' => 'Registration',
        'label' => 'Label',
        'seats' => 'Seats',
        'status' => 'Status',
        'status_operationnal' => 'Operational',
        'status_maintenance' => 'In Maintenance',
        'status_broken' => 'Broken',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'save' => 'Save',
        'language' => 'Language',
        'journey_management' => 'Journey Management',
        'add_journey' => 'Add Journey',
        'update_journey' => 'Update Journey',
        'driver' => 'Driver',
        'vehicule' => 'Vehicule',
        'label' => 'Label',
        'date_from' => 'Date From',
        'date_to' => 'Date To',
        'time_start' => 'Time Start',
        'time_end' => 'Time End'
        ,'driver_management' => 'Driver Management'
        ,'add_driver' => 'Add Driver'
        ,'driver_status' => 'Status'
        ,'driver_member' => 'Member'
        ,'available' => 'Available'
        ,'rest' => 'Rest'
        ,'off_duty' => 'Off duty'
        ,'update_driver' => 'Update Driver'
        ,'error_required' => 'Email and password required'
        ,'error_contact_api' => 'Unable to contact API'
        ,'error_credentials' => 'Invalid credentials'
    ],
    'fr' => [
        'login_title' => 'Connexion CVLG',
        'email' => 'Email',
        'password' => 'Mot de passe',
        'login' => 'Connexion',
        'welcome' => 'Bienvenue',
        'logged_in' => 'Vous êtes connecté.',
        'logout' => 'Déconnexion',
        'member_management' => 'Gestion des membres',
        'first_name' => 'Prénom',
        'last_name' => 'Nom',
        'member_type' => 'Type de membre',
        'address' => 'Adresse',
        'street' => 'Rue',
        'street_number' => 'Numéro',
        'postal_code' => 'Code postal',
        'city' => 'Ville',
        'country' => 'Pays',
        'add_member' => 'Ajouter un membre',
        'vehicle_management' => 'Gestion des véhicules',
        'add_vehicle' => 'Ajouter un véhicule',
        'name' => 'Nom',
        'registration' => 'Immatriculation',
        'label' => 'Libellé',
        'seats' => 'Places',
        'status' => 'Statut',
        'status_operationnal' => 'Opérationnel',
        'status_maintenance' => 'En maintenance',
        'status_broken' => 'En panne',
        'delete' => 'Supprimer',
        'edit' => 'Éditer',
        'save' => 'Enregistrer',
        'language' => 'Langue',
        'journey_management' => 'Gestion des trajets',
        'add_journey' => 'Ajouter un trajet',
        'update_journey' => 'Modifier le trajet',
        'driver' => 'Conducteur',
        'vehicule' => 'Véhicule',
        'label' => 'Libellé',
        'date_from' => 'Date début',
        'date_to' => 'Date fin',
        'time_start' => 'Heure début',
        'time_end' => 'Heure fin',
        'driver_management' => 'Gestion des chauffeurs'
        ,'add_driver' => 'Ajouter un chauffeur'
        ,'driver_status' => 'Statut'
        ,'driver_member' => 'Membre'
        ,'available' => 'Disponible'
        ,'rest' => 'Repos'
        ,'off_duty' => 'Hors service'
        ,'update_driver' => 'Mettre à jour le chauffeur'
        ,'error_required' => 'Email et mot de passe requis'
        ,'error_contact_api' => "Impossible d'accéder à l'API"
        ,'error_credentials' => 'Identifiants invalides'
    ],
    'de' => [
        'login_title' => 'CVLG Anmeldung',
        'email' => 'E-Mail',
        'password' => 'Passwort',
        'login' => 'Anmelden',
        'welcome' => 'Willkommen',
        'logged_in' => 'Sie sind eingeloggt.',
        'logout' => 'Abmelden',
        'member_management' => 'Mitgliederverwaltung',
        'first_name' => 'Vorname',
        'last_name' => 'Nachname',
        'member_type' => 'Mitgliedstyp',
        'address' => 'Adresse',
        'street' => 'Straße',
        'street_number' => 'Nummer',
        'postal_code' => 'PLZ',
        'city' => 'Stadt',
        'country' => 'Land',
        'add_member' => 'Mitglied hinzufügen',
        'vehicle_management' => 'Fahrzeugverwaltung',
        'add_vehicle' => 'Fahrzeug hinzufügen',
        'name' => 'Name',
        'registration' => 'Kennzeichen',
        'label' => 'Bezeichnung',
        'seats' => 'Sitzplätze',
        'status' => 'Status',
        'status_operationnal' => 'Einsatzbereit',
        'status_maintenance' => 'In Wartung',
        'status_broken' => 'Defekt',
        'delete' => 'Löschen',
        'edit' => 'Bearbeiten',
        'save' => 'Speichern',
        'language' => 'Sprache',
        'journey_management' => 'Fahrtverwaltung',
        'add_journey' => 'Fahrt hinzufügen',
        'update_journey' => 'Fahrt bearbeiten',
        'driver' => 'Fahrer',
        'vehicule' => 'Fahrzeug',
        'label' => 'Bezeichnung',
        'date_from' => 'Datum von',
        'date_to' => 'Datum bis',
        'time_start' => 'Startzeit',
        'time_end' => 'Endzeit',
        'driver_management' => 'Fahrerverwaltung'
        ,'add_driver' => 'Fahrer hinzufügen'
        ,'driver_status' => 'Status'
        ,'driver_member' => 'Mitglied'
        ,'available' => 'Verfügbar'
        ,'rest' => 'Pause'
        ,'off_duty' => 'Außer Dienst'
        ,'update_driver' => 'Fahrer aktualisieren'
        ,'error_required' => 'E-Mail und Passwort erforderlich'
        ,'error_contact_api' => 'API konnte nicht erreicht werden'
        ,'error_credentials' => 'Ungültige Anmeldedaten'
    ],
    'it' => [
        'login_title' => 'Accesso CVLG',
        'email' => 'Email',
        'password' => 'Password',
        'login' => 'Accedi',
        'welcome' => 'Benvenuto',
        'logged_in' => 'Sei connesso.',
        'logout' => 'Disconnetti',
        'member_management' => 'Gestione membri',
        'first_name' => 'Nome',
        'last_name' => 'Cognome',
        'member_type' => 'Tipo di membro',
        'address' => 'Indirizzo',
        'street' => 'Via',
        'street_number' => 'Numero',
        'postal_code' => 'CAP',
        'city' => 'Città',
        'country' => 'Paese',
        'add_member' => 'Aggiungi membro',
        'save' => 'Salva',
        'vehicle_management' => 'Gestione veicoli',
        'add_vehicle' => 'Aggiungi veicolo',
        'name' => 'Nome',
        'registration' => 'Targa',
        'label' => 'Etichetta',
        'seats' => 'Posti',
        'status' => 'Stato',
        'status_operationnal' => 'Operativo',
        'status_maintenance' => 'In manutenzione',
        'status_broken' => 'Guasto',
        'delete' => 'Elimina',
        'edit' => 'Modifica',
        'language' => 'Lingua',
        'journey_management' => 'Gestione viaggi',
        'add_journey' => 'Aggiungi viaggio',
        'update_journey' => 'Aggiorna viaggio',
        'driver' => 'Autista',
        'vehicule' => 'Veicolo',
        'label' => 'Etichetta',
        'date_from' => 'Data inizio',
        'date_to' => 'Data fine',
        'time_start' => 'Ora inizio',
        'time_end' => 'Ora fine',
        'driver_management' => 'Gestione autisti'
        ,'add_driver' => 'Aggiungi autista'
        ,'driver_status' => 'Stato'
        ,'driver_member' => 'Membro'
        ,'available' => 'Disponibile'
        ,'rest' => 'Riposo'
        ,'off_duty' => 'Fuori servizio'
        ,'update_driver' => 'Aggiorna autista'
        ,'error_required' => 'Email e password obbligatorie'
        ,'error_contact_api' => "Impossibile contattare l'API"
        ,'error_credentials' => 'Credenziali non valide'
    ]
];

function t(string $key): string {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}
?>
